// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmczskdspysdfscbecud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY3pza2RzcHlzZGZzY2JlY3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzIxMTksImV4cCI6MjA1NTA0ODExOX0.mLNsSFlmhsWKutAZ98wJLrklVia3OZAeOiCmnICTks4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);